apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: cli-v02
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cli-v02
    app.kubernetes.io/part-of: ec-v02
  name: cli-v02
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: cli-v02
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: cli-v02
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-contract-tenant/ec-v02/cli-v02@sha256:ea770cb5132c5a606c4bbeccdfe0b7f44aebb32e1f838073d0c75fee35a01646
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
