apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: cli-v02
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-contract-tenant/ec-v02/cli-v02@sha256:a0949fd4c67472af8a9b3c0883d5b949f070193477610d0531f3718e022bc655
        name: container-image
        resources: {}
status: {}
